const VERTICAL_MENU_WIDTH = 220;
const HORIZONTAL_MENU_HEIGHT = 180;

const BUTTON_MODE = {
  LINK: 'LINK'
}

const BUTTON_APPEARANCE = {
  WHITE: 'white'
}

const DEFAULT_BRUSH_SIZE = 20;
const DEFAULT_BG_COLOR = '#ffffff';
const DEFAULT_BRUSH_COLOR = '#000000';
const DEFAULT_BRUSH_OPACITY = 100

export {
  VERTICAL_MENU_WIDTH,
  HORIZONTAL_MENU_HEIGHT,
  DEFAULT_BRUSH_SIZE,
  DEFAULT_BG_COLOR,
  DEFAULT_BRUSH_COLOR,
  DEFAULT_BRUSH_OPACITY,
  BUTTON_MODE,
  BUTTON_APPEARANCE
};
